### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by iw6ovz** [madchicken/homebridge-comelit-hub#23]
The installation produce this error:

![ScreenHunter_02 Jul  30 17 25](https://user-images.githubusercontent.com/55229396/88941850-d0950100-d289-11ea-895b-47d1398dc7b7.jpg)

and the homebridge this:
![image](https://user-images.githubusercontent.com/55229396/88942179-341f2e80-d28a-11ea-8e4f-de4e5eda73da.png)

**Comment by madchicken** [comment]
Could you tell me the version of your HUB firmware? You should be able to check it from the HUB HTTP admin page (http://[HUB_IP])

**Comment by iw6ovz** [comment]
Hi, the firmware versione is 1.02.
Tnx

**Comment by madchicken** [comment]
Are you sure you have the new HUB? Maybe you have the serial bridge...in that case you should use the other plugin (homebridge-comelit-sb)

**Comment by iw6ovz** [comment]
:-) yes, I'm dure. Just instslled.

**Comment by iw6ovz** [comment]
This one:

![Screenshot_20200810-151419_Chrome](https://user-images.githubusercontent.com/55229396/89786467-41ef7200-db1c-11ea-9363-3e0d383b21b2.jpg)

**Comment by madchicken** [comment]
Weird, I installed it a year ago an my web interface reports version 1.2.2

<img width="1209" alt="Screenshot 2020-08-10 at 15 28 09" src="https://user-images.githubusercontent.com/296618/89787680-2e450b00-db1e-11ea-937d-07348ec63012.png">

I know there are issues with version 1.3 but I still could not try it.
Please send me more information about your current plugin config and please, set homebridge in debug mode (through the settings UI page) and the send me the start up logs (You can copy and paste them from the web interface)

**Comment by Just-inc-ace** [comment]
Don't know if this is related but I had to change this line:
`const HUB_ID = '0025291701EC';`
in
`const HUB_ID = 'MY_MAC_ADDRESS_OF_MY_COMELITHUB';`

This is located in line 23 of comelit-client.js in node_modules/homebridge-comelit-platform/node_modules/comelit-client/dist/
As this is declared a constant and not a variable in the configuration of the module

**Comment by madchicken** [comment]
@Just-inc-ace Ah! This is something I forgot, I'll fix it in the next release...thanks!

**Comment by madchicken** [comment]
Fixed in the last release (HUB id is now auto discovered)
