### ISSUE TITLE
Works well once 

### ISSUE THREAD

**Issue by jonydebu** [madchicken/homebridge-comelit-hub#25]
Hi guy , fantastic job . My issue is  when i activate something (light , thermostat , ..) it works fine but the second time that i try to use it again an exclamation point came to my iphone screen  .With Siri got the same way first time she works well but second time she says "thermostat , light , ... don´t answer" . After rebooting got always the same .  Need some help . Thanks in advance

**Comment by madchicken** [comment]
Can you share the homebridge version you are using?

**Comment by jonydebu** [comment]
Hi mad , the homebridge version is 1.1.3 , think is the last one .

**Comment by madchicken** [comment]
Please, activate the debug mode in homebridge, capture some log and link it here. Also try the new homebridge 2.0.0beta that solves a lot of problems with accessories not responding

**Comment by madchicken** [comment]
@jonydebu Could you check the latest plugin version, it might solve this issue...

**Comment by jonydebu** [comment]
> @jonydebu Could you check the latest plugin version, it might solve this issue...

Test new version , and now it works perfectly . Great job Paolo , thanks !!

**Comment by madchicken** [comment]
Glad to hear that!
