### ISSUE TITLE
Is it compatible?

### ISSUE THREAD

**Issue by iShortOne** [madchicken/homebridge-comelit-hub#27]
Hi everyone!
I just have a question, is this compatible?
Thanks in advance!

![BB5413D7-53F1-4231-B0ED-1FA40C570AC1](https://user-images.githubusercontent.com/36272818/93685738-c802bf00-fab1-11ea-8927-1eccca8fa428.jpeg)

**Comment by jonydebu** [comment]
Hi , you have an plug-in  for serial bridge users . Test it and comment.

**Comment by ciapamusche** [comment]
I have the same. Fully working
