### ISSUE TITLE
aggiungere gestione dispositivi di tipo altro

### ISSUE THREAD

**Issue by 27andrea** [madchicken/homebridge-comelit-hub#28]
buongiorno,chiedo se è possibile aggiungere la gestione dei dispositivi altro.
un esempio è il carraio

**Comment by madchicken** [comment]
Ciao, non sono sicuro di capire: mi puoi dire esattamente come vedi questi dispositivi nell'op di come lit? In HomeKit ogni device è ben definito come tipo (luce, termostato, tapparella). Un dispositivo `altro` come dovrei configurarlo?

**Comment by 27andrea** [comment]
Ciao,nell'app comelit viene visto come un dispositivo altro 
Allego foto 
Sarebbe da configurare come se fosse un interruttore che da un impulso accendi e 
![A27C1752-895F-4656-BBB7-DC462583561A](https://user-images.githubusercontent.com/5239608/97113394-52aa8f80-16ea-11eb-89de-f0fe35161447.jpeg)
spegni. É per aprire un cancello

**Comment by madchicken** [comment]
Ciao, potresti installare l'ultima versione del plugin, riavviare homebridge ed inviarmi i log?

**Comment by 27andrea** [comment]
ciao ecco qui
[Uploading homebridge.log.txt…]()

**Comment by madchicken** [comment]
Credo che l'upload non abbia funzionato...puoi usare https://gist.github.com se vuoi

**Comment by 27andrea** [comment]
riprovo,
[homebridge.log.txt](https://github.com/madchicken/homebridge-comelit-hub/files/5477128/homebridge.log.txt)

**Comment by madchicken** [comment]
Ti chiedo scusa, potresti aggiornare di nuovo il plugin e ripetere il processo? Sarebbe anche d'aiuto se tu aprissi il cancello dall'app come lit, cosi' posso vedere come funziona

**Comment by 27andrea** [comment]
ciao,ecco qui,il dispositivo è quello chiamato carraio.
ho provato ad eseguirlo 3 volte.
apertura,stop carraio e chiusura,in realtà è sempre lo stesso impulso.
grazie
[homebridge.log(1).txt](https://github.com/madchicken/homebridge-comelit-hub/files/5477233/homebridge.log.1.txt)

**Comment by 27andrea** [comment]
dimenticavo,grazie per il supporto.

**Comment by madchicken** [comment]
Prova con la versione 2.5.0 del plugin, ora dovresti poter mappare i device di tipo OTHERS

**Comment by 27andrea** [comment]
Ciao,
perfetto!!!
ora mi mappa il dispositivo carraio e funziona correttamente 
grazie mille 
Andrea
