### ISSUE TITLE
Received message could not be processed on instant power sensor

### ISSUE THREAD

**Issue by tomasell** [madchicken/homebridge-comelit-hub#31]
Hi there,
in my own environment, there are 3 Comelit sensors that report instant power consumption.
is it possibile to configure them as [Power Management](https://developers.homebridge.io/#/service/PowerManagement) sensors?

I'd like to collaborate in this repo with pull requests, but I'm still learning your library right now.
In the meantime, thanks for the support.

> [15/11/2020, 17:45:43] [Comelit] Updating DOM#CN#12.1 with data {"id":"DOM#CN#12.1","type":11,"sub_type":15,"sched_status":"0","sched_lock":"1970-01-01 01:00:00","status":"255","powerst":"255","instant_power":"0.000000"}
[15/11/2020, 17:45:43] [Comelit] Reporting instant consumption of 0.000000Wh
Received message could not be processed {
  req_type: 0,
  req_sub_type: -1,
  obj_id: 'DOM#CN#12.1',
  out_data: [
    {
      id: 'DOM#CN#12.1',
      type: 11,
      sub_type: 15,
      sched_status: '0',
      sched_lock: '1970-01-01 01:00:00',
      status: '255',
      powerst: '255',
      instant_power: '0.000000'
    }
  ],
  status: NaN
}

> [15/11/2020, 17:45:46] [Comelit] Updating DOM#CN#11.1 with data {"id":"DOM#CN#11.1","type":11,"sub_type":15,"sched_status":"0","sched_lock":"1970-01-01 01:00:00","status":"255","powerst":"255","instant_power":"1232.000000"}
[15/11/2020, 17:45:46] [Comelit] Reporting instant consumption of 1232.000000Wh
Received message could not be processed {
  req_type: 0,
  req_sub_type: -1,
  obj_id: 'DOM#CN#11.1',
  out_data: [
    {
      id: 'DOM#CN#11.1',
      type: 11,
      sub_type: 15,
      sched_status: '0',
      sched_lock: '1970-01-01 01:00:00',
      status: '255',
      powerst: '255',
      instant_power: '1232.000000'
    }
  ],
  status: NaN
}

> [15/11/2020, 17:45:46] [Comelit] Updating DOM#CN#10.1 with data {"id":"DOM#CN#10.1","type":11,"sub_type":15,"sched_status":"0","sched_lock":"1970-01-01 01:00:00","status":"255","powerst":"255","instant_power":"44.000000"}
[15/11/2020, 17:45:46] [Comelit] Reporting instant consumption of 44.000000Wh
Received message could not be processed {
  req_type: 0,
  req_sub_type: -1,
  obj_id: 'DOM#CN#10.1',
  out_data: [
    {
      id: 'DOM#CN#10.1',
      type: 11,
      sub_type: 15,
      sched_status: '0',
      sched_lock: '1970-01-01 01:00:00',
      status: '255',
      powerst: '255',
      instant_power: '44.000000'
    }
  ],
  status: NaN
}

**Comment by tomasell** [comment]
it looks like that:
- the object type is the right one ( POWER_SUPPLIER = 11 ) ;
- the subtype is the right one ( CONSUMPTION = 15 );
- log prints `Reporting instant consumption of ${data.instant_power}Wh`


So, what do you suggest to do?

**Comment by tomasell** [comment]
Hi @madchicken ,
could you help me to resolve this issue?
Thanks a lot.

**Comment by madchicken** [comment]
Hi. The plugin is already able to map those sensors, but unfortunately HomeKit does not support them. It supports Power Management but they don't do anything. The current plugin implementation is able to expose power consumption as a Prometheus metric (http://prometheus.io/). I use it to monitor my house. The improvement would be to use fake-gato history, but is still something I didn't have time to do

**Comment by tomasell** [comment]
Ciao! Posso chiedere una CR su questa tematica?
Al momento ho una trifase con 3 sensori di consumo per singola fase.
Nel momento in cui invio i dati a prometheus, i valori vengono riuniti in unico dato. Sarebbe possibile dividere i dati, come è già per gli altri sensori di temperatura / umidità, in modo da avere una entry per ogni fase?

A disposizione per condividere i log dei messaggi. Grazie!

**Comment by madchicken** [comment]
Interessante configurazione...una domanda: li vedi come tre sensori diversi giusto?

**Comment by tomasell** [comment]
Si vedo che varia id ` DOM#CN#`
Riporto i 3 messaggi che vedo dai log:

> [20/10/2022, 15:03:26] [Comelit] Updating DOM#CN#10.1 with data {"id":"DOM#CN#10.1","type":11,"sub_type":15,"sched_status":"0","sched_lock":"1970-01-01 01:00:00","status":"255","powerst":"255","instant_power":"220.000000"}
[20/10/2022, 15:03:26] [Comelit] Reporting instant consumption of 220Wh
Message processed. Message queue size is now 0


> [20/10/2022, 15:03:40] [Comelit] Updating DOM#CN#11.1 with data {"id":"DOM#CN#11.1","type":11,"sub_type":15,"sched_status":"0","sched_lock":"1970-01-01 01:00:00","status":"255","powerst":"255","instant_power":"1012.000000"}
[20/10/2022, 15:03:40] [Comelit] Reporting instant consumption of 1012Wh
Message processed. Message queue size is now 0


> [20/10/2022, 15:03:51] [Comelit] Updating DOM#CN#12.1 with data {"id":"DOM#CN#12.1","type":11,"sub_type":15,"sched_status":"0","sched_lock":"1970-01-01 01:00:00","status":"255","powerst":"255","instant_power":"0.000000"}
[20/10/2022, 15:03:51] [Comelit] Reporting instant consumption of 0Wh
Message processed. Message queue size is now 0

**Comment by tomasell** [comment]
Confermo che vedo i dati con successo, grazie!
