### ISSUE TITLE
Device ID continues to change

### ISSUE THREAD

**Issue by 27andrea** [madchicken/homebridge-comelit-hub#42]
Hi,
I have condigured the homebridge with comelit hub.
I use this bridge on home assistant.
I have seen that every reboot the id of the devices change and create duplicates on home assistant.
I have flag Enabled on comelit homebridge (avoid duplicates)
Can you help me?
Thanks

**Comment by 27andrea** [comment]
This happens on only other devices.for example carraio

**Comment by madchicken** [comment]
@27andrea This is really weird, since IDs are generated by reading the internal mapping of the house, that is provided by the Comelit system itself. What kind of device is "carraio"?

**Comment by 27andrea** [comment]
Carraio is a "other" device
Thanks

**Comment by madchicken** [comment]
Can you try the latest version starting homebridge in debug mode? It should log the house mapping at every startup (is a big json). Please attach a couple of logs so I can understand why it is generating different ids

**Comment by 27andrea** [comment]
hi ,it seems that the device doesn't change anymore but I have homebridge connected to an home assistant and it continue to put available/not available the devices.
after 1 minutes it come back online and go on

**Comment by madchicken** [comment]
Please, attach some log so I can understand if the problem is in the plugin or in the way the hub reports the status of the device
