### ISSUE TITLE
Home entry compatibility?

### ISSUE THREAD

**Issue by johnpatrickbailey** [madchicken/homebridge-comelit-hub#56]
Apologies if this is off-topic for this plugin (which I notice is limited to HUB integration), but do you have any insight into whether it’s possible to expose devices in Comelit’s home entry line of products to homebridge? I have a [6741w](https://pro.comelitgroup.com/en-us/product/6741w) entry monitor that’s compatible with Alexa and Google. You seem to have more experience integrating Comelit devices than anyone else I could find, I just thought I would ask.

**Comment by madchicken** [comment]
You should check my other project [here](https://github.com/madchicken/homebridge-comelit-icona), it should work for you (but it just supports door opening for now)
