### ISSUE TITLE
[BUG] ReadMe link to Sentry DSN is incorrect

### ISSUE THREAD

**Issue by jaknz** [madchicken/homebridge-comelit-hub#65]
**Describe the bug**
ReadMe file links to https://sentry.com/ for information on what a Sentry DSN is. This is not the correct site, as sentry.com is a business insurance broker. 

**To Reproduce**
1. Go to Project ReadMe
2. Click on http://sentry.com
4. See that this has nothing to do with technical DSN connections

**Expected behavior**
Maybe more information on what the sentry dsn is, and a link to documentation?

**Screenshots**

**Desktop (please complete the following information):**
 - Node version: [e.g. 16.6.6]
 - Homebridge version [e.g. 1.5.0]
 - Plugin Version [e.g. 2.6.3]

**Startup logs**
An extract of the startup log of homebridge

**Comment by madchicken** [comment]
Thanks. Sentry changed name and I forgot about this. Also, I am not using it anymore, so I should remove it from the project. I'll fix it
