### ISSUE TITLE
contribute to old version of SimpleBUS Bridge .  The Serial Bridge

### ISSUE THREAD

**Issue by ciapamusche** [madchicken/homebridge-comelit-hub#8]
hey guys. i'll try to give my contribute i know is not very much

https://github.com/openhab/openhab-addons/issues/4205

please check this post. I inserted some commands and status request page

**Comment by madchicken** [comment]
Hey, thanks for opening this. I'd love to help with the old version of the SerialBUS, but to do that I need more information about how it works. I started reading around all the links from the thread above, but I need something more detailed. Maybe someone can provide a HAR file of the current web interface.
To do that, open Chrome browser, open developers tools and then, from the browser window, navigate to the web interface of the SerialBUS. Log in and, for example, turn on and off a light. Then Stop recording in the DevTools console (press the red circle icon in the upper left corner of Network panel) and right click on the list you have below, than choose "Save all as HAR with content". From there we can start understanding how to build the code for a new plugin or an adapter for this one.

**Comment by madchicken** [comment]
@ciapamusche do you think you can provide the HAR file?

**Comment by ciapamusche** [comment]
sorry for delay madchicken. i will provide soon. thank you.

do you think is possible create a file directly to put inside a raspberry?

**Comment by madchicken** [comment]
I implemented a new plugin that supports the old Comelit Serial Bridge. Find it [here](https://github.com/madchicken/homebridge-comelit-sb)
